baseURL = "https://shivamgupta211.github.io"
languageCode = "en-us"
title = "Shivam Gupta | Software Engineer"
theme = "resume"

[params]
    firstName = "Shivam"
    lastName = "Gupta"
    address = "Gurugram, Harayana"
    phone = "+91 75700-11066"
    role = "Software Engineer"
    contactNote = "Software Engineer"
    title = "Shivam Gupta | Software Engineer"
    profileImage = "img/shivamgupta_profile.png"
    email = "shivamgupta211@gmail.com"
    description = "Software Engineer with experience in building highly sclable SaaS products."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showBlogs = false
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/shivamgupta211/"

[[params.handles]]
    name = "Twitter"
    link = "https://www.twitter.com/in/shivamgupta211/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/shivamgupta211/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/5547512"
    icon = "stack-overflow"

[[params.handles]]
    name = "Google+"
    link = "https://plus.google.com/u/0/113750680604298174547"
    icon = "google-plus"

[params.google.analytics]
    trackerID = ""
