baseurl = "https://shivamgupta211.github.io/blog/"
title = "Shivam Gupta | Blog"
theme = "hugo_theme_aglaus"

googleAnalytics = "UA-XXXXXXXX-XX" # Optional
disqusShortname = "XYW"

[params]
  description = "Shivam Gupta"
  dateformat = "Jan 2, 2006" # Optional
  absUrl = "https://shivamgupta211.github.io/"
  metaTitle = "Blog"
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/shivamgupta_profile.png"
  name = "Shivam Gupta"
  description = "<p>Software Enginner ang GitOps</p>"

[outputs]
page = [ "HTML", "AMP" ]